### ISSUE TITLE
Forrita basic movement fyrir karaktera

### ISSUE THREAD

**Issue by ingosibbason** [ingosibbason/Leikjaforritun2#29]
Fyrir sprites án walk animation

Player 1 
 - Move: WASD
 - Attack: R eða V
 - Charge attack: T eða B

Player 2
 - Move: Örvartakkar
 - Attack:  , (Komma)
 - Charge attack: . (Punktur)

Allar hugmyndir um takka vel þegnar

**Comment by Dumydevel** [comment]
Búin að gera basic movement
